services:
  - type: web
    name: adk-hotel-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db # Name of your Neon DB on Render
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_BASE_URL
        fromService:
          type: web
          name: adk-hotel-bot
          property: url